"""groups_rbac

Revision ID: 7c8e21a3f82b
Revises: 1c6ee173a43c
Create Date: 2026-08-02 14:00:33.627665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c8e21a3f82b'
down_revision: Union[str, Sequence[str], None] = '1c6ee173a43c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_invites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_invites_group_id'), 'group_invites', ['group_id'], unique=False)
    op.create_index(op.f('ix_group_invites_token_hash'), 'group_invites', ['token_hash'], unique=True)
    op.create_table('group_memberships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('owner', 'member', name='group_role'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'user_id', name='uq_group_memberships_group_id_user_id')
    )
    op.create_index(op.f('ix_group_memberships_group_id'), 'group_memberships', ['group_id'], unique=False)
    op.create_index('ix_group_memberships_one_owner_per_group', 'group_memberships', ['group_id'], unique=True, postgresql_where=sa.text("role = 'owner'"))
    op.create_index(op.f('ix_group_memberships_user_id'), 'group_memberships', ['user_id'], unique=False)
    op.add_column('projects', sa.Column('group_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_projects_group_id'), 'projects', ['group_id'], unique=False)
    op.create_foreign_key(
        'fk_projects_group_id_groups', 'projects', 'groups', ['group_id'], ['id'], ondelete='RESTRICT'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_projects_group_id_groups', 'projects', type_='foreignkey')
    op.drop_index(op.f('ix_projects_group_id'), table_name='projects')
    op.drop_column('projects', 'group_id')
    op.drop_index(op.f('ix_group_memberships_user_id'), table_name='group_memberships')
    op.drop_index('ix_group_memberships_one_owner_per_group', table_name='group_memberships', postgresql_where=sa.text("role = 'owner'"))
    op.drop_index(op.f('ix_group_memberships_group_id'), table_name='group_memberships')
    op.drop_table('group_memberships')
    sa.Enum(name='group_role').drop(op.get_bind(), checkfirst=True)
    op.drop_index(op.f('ix_group_invites_token_hash'), table_name='group_invites')
    op.drop_index(op.f('ix_group_invites_group_id'), table_name='group_invites')
    op.drop_table('group_invites')
    op.drop_table('groups')
    # ### end Alembic commands ###
